### ISSUE TITLE
Bootstrap Carousel

### ISSUE THREAD

**Issue by fsciuti** [tjoskar/ng-lazyload-image#164]
Hello, is it possible to integrate _lazyload-image_ component with [Bootstrap Carousel Component](http://valor-software.com/ngx-bootstrap/#/carousel)?

I don't understand how to detect _scrollObservable_ parameter to attach.

Thank you so much!

**Comment by tjoskar** [comment]
Hi,

You should just need to add `[defaultImage]="defaultImage" [lazyLoad]="image"`, like:

```html
<carousel>
  <slide>
    <img src="default-image.jpg" lazyLoad="1.jpg">
  </slide>
  <slide>
    <img src="default-image.jpg" lazyLoad="2.jpg">
  </slide>
<carousel>
```

This may however not work if the carousel is visible on page load (before the user scrolls). What you can do in that case is to add a check that will disable the image if the image is not shown, ie.
```
<slide #slide1>
  <img [ngIf]="slide1.offsetParent" src="default-image.jpg" lazyLoad="1.jpg">
</slide>
```

That can, however, become a performance problem since `ng-lazyload` will re-instantiate every time the image becomes visible.

Can you try to add `lazyLoad` (eg. <img src="default-image.jpg" [lazyLoad]="myImage">) to your images and that we can take it from there?

**Comment by tjoskar** [comment]
@fsciuti, Did you solve the issue?
