### ISSUE TITLE
Lazy loading background-image on an element doesn't work with nolimit4web/swiper

### ISSUE THREAD

**Issue by mhdSid** [tjoskar/ng-lazyload-image#286]
Lazy loading background-image on an element doesn't work with nolimit4web/swiper http://idangero.us/swiper/

It works perfectly fine on a normal element, however, if the element is a child of a swiper carousel from  nolimit4web/swiper, the background-image value is always the default image value.

**Comment by tjoskar** [comment]
Hi,

That is (most likely) because `ng-lazyload-image` only will listen for scroll events on `window` per default. If some other library triggers the visibility of an image, `ng-lazyload-image` will not know about it unless we inform it, eg. by using [scroll observable](https://github.com/tjoskar/ng-lazyload-image#scrollobservable-optional).

Can you create a create a small gitrepo/stackblitz/plnkr where you can reproduce the problem, eg. by forking this: https://stackblitz.com/edit/angular-9guzc4

**Comment by mhdSid** [comment]
Hello,
I tried creating an observable object
`this.scroll = Observable.fromEvent(document.getElementsByClassName('swiper-container')[0], 'slideChangeTransitionStart');`

and passed it like this

`[scrollObservable]="scroll"`

However, this didn't work out successfully

**Comment by mhdSid** [comment]
Hello There,

It worked if I dispatch a custom event like this:

```
var swiper = new Swiper('carousel, {
  on: {
        slideNextTransitionEnd: () => {
          var event = document.createEvent('Event');
          event.initEvent('scrolll', true, true);
          swiperContainerElement.dispatchEvent(event);
        };
      }
};
```

then 

```
this.scrollObservable = Observable.fromEvent(document.getElementsByClassName('swiper-container')[0], 'scrolll');

<div class="lazy-backimg" [scrollObservable]="scrollObservable" [lazyLoad]="track.image" [defaultImage]="defaultimage" [offset]="10"></div>
```

Success
