### ISSUE TITLE
Is there a way to start loading remaining images once every image in the viewport is already loaded?

### ISSUE THREAD

**Issue by AlexLomm** [tjoskar/ng-lazyload-image#309]
The title is pretty much self-explanatory - I'm looking for a way to load the remaining images, once every image present in the viewport is already loaded. 

For example, there might be a case when user stops to read something on the page and then continues to scroll. Is it possible to utilize that time window to pre-load the below images?

P.S
Love this package! Keep up the good work!

**Comment by tjoskar** [comment]
Hi @AlexLomm, 
First of all: Sorry for the late reply.

This is a tough one and is not supported out of the box. The only solution I can think of is to create a component with high priority images and have a `Subject` to keep track of loaded images (with the `onLoad`-output) and then have a component that loads (low-priority) images when the `Subject` emits a value. It will however not be pretty ;)

Since the browser automatically gives [images low priority](https://developers.google.com/web/tools/chrome-devtools/network-performance/understanding-resource-timing) it might be better to load all images at once.

It should be quite easy to create a custom component if you just want to keep the 'default image'-functionality, without lazyloading. Let me know if you want to discuss a solution for this component.

**Comment by AlexLomm** [comment]
Ok, got it. Thanks for the reply
