### ISSUE TITLE
Can't show image with [innerHTML] string html binding

### ISSUE THREAD

**Issue by julpane** [tjoskar/ng-lazyload-image#321]
Hi, 
I have successfully implemented lazy load image with default environment,
`<div class="img-lazyload-canvas"><div class="img-lazyload img-responsive" lazyLoad="http://www.freeimageslive.com/galleries/workplace/tools/pics/architect_design.jpg">/div></div>`

but if i save to database as html string and bind with [innerHTML], image not showing.
`<div class="timeline-content" [innerHTML]="article.content"></div>`

Anyone can help.?

**Comment by tjoskar** [comment]
Hi @julpane,

You can't use `innerHTML` to dynamic create angular specific modules. I googled on the issue and found this StackOverflow question: https://stackoverflow.com/questions/38888008/how-can-i-use-create-dynamic-template-to-compile-dynamic-component-with-angular 

I'm closing this since it is an angular specific question :)
