### ISSUE TITLE
Compiler errors when upgrading my project to angular v6

### ISSUE THREAD

**Issue by speige** [tjoskar/ng-lazyload-image#330]
Pull request: https://github.com/tjoskar/ng-lazyload-image/pull/331

**Comment by speige** [comment]
For anyone wanting this before it gets pulled & hits npm:

replace this to your package.json
"ng-lazyload-image": "3.4.2",
with
"ng-lazyload-image": "github:speige/ng-lazyload-image"

**Comment by tjoskar** [comment]
Hi @speige,

As I was writing in #331; this library should work with Angular@6 but I agree that it is some problem with the release: https://stackblitz.com/edit/ng-lazyload-image-330?file=app%2Fapp.component.html

I don't think we should upgrade to Angular 6 since it will drop support for those how still uses Angular 4 (?). 

I don't really know what the issue is and I welcome any help I can get.

**Comment by speige** [comment]
I tested the latest version of the pull request on both angular 5 & angular 6 & they both seem to be working. I haven't tried with angular 4.

I was surprised both 5 & 6 work, because the pull request still uses newer versions of angular & rxjs in package.json. Maybe because peerDepencencies is back to the lower versions? I don't really know the inner workings of webpack, but maybe it's including both versions of rxjs in the final bundle?

**Comment by tjoskar** [comment]
I have been thinking about this. What if we didn't compile `ng-lazyload-image` before publishing but let the user compiles it. Hear me out, if we don't use `ngc` we can easily support multiple versions of angular and we do not need to upgrade angular to support a new one because the compiling is done at the user end. We only need to ship the ts files, the reset is taking care of by webpack/fuzebox/rollup/etc.

There is two way of doing this:
1. We can use the `install`-script and run `ngc` when the user runs `npm install ng-lazyload-image`
2. We do not do anything and let the user compiles it with the rest of the application.

(I was doing this when I created [react-lazyload-img](https://github.com/tjoskar/react-lazyload-img))

**Comment by speige** [comment]
I've tested with angular v6 final & the original ng-lazyload-image without my pull request is working fine. I guess I shouldn't adopt an RC too quickly :)

closing this issue.
