### ISSUE TITLE
Supports background images, not work

### ISSUE THREAD

**Issue by vangtry** [tjoskar/ng-lazyload-image#386]
Im tryin to use into div with background but the default and final image are loaded

this my code

.html

![image](https://user-images.githubusercontent.com/26026773/56337166-79891c80-6169-11e9-919d-3a74617ffdb5.png)

.ts

![image](https://user-images.githubusercontent.com/26026773/56337186-9160a080-6169-11e9-9f7c-29eb97c1939a.png)

.module

![image](https://user-images.githubusercontent.com/26026773/56337194-a2111680-6169-11e9-8361-7481c975dea3.png)

chrome console
![image](https://user-images.githubusercontent.com/26026773/56337226-cd940100-6169-11e9-90b5-850716a7f97c.png)

**Comment by vangtry** [comment]
My solution was add the properties of default image tag into the div with bg

![image](https://user-images.githubusercontent.com/26026773/56337532-670fe280-616b-11e9-9d57-3129696566b2.png)


please confirm if this way is how expected works ? because in the documentation its no clear how implement this feature

chrome console

![image](https://user-images.githubusercontent.com/26026773/56337596-b2c28c00-616b-11e9-8d29-8c4f8e14625a.png)

**Comment by tjoskar** [comment]
> default and final image are loaded
That is by design.

This is the procedure:
1. The default image is loaded right away (as you put in `style="background-image: url('...')`. 
2. When the images comes into the viewport, the lazyloaded image starts loading. 
3. The default image will be shown until the lazyloaded image is loaded.
4. When the lazyloaded image is loaded, the default image is replaced with the lazyloaded.
5. If anything goes wrong, the default images is replaced with the error image if provided

I can create an example if you want.

**Comment by tjoskar** [comment]
https://codesandbox.io/s/jp7nzr0o5
Take a look at `app/app.component.ts` and `app/app.component.html`

**Comment by tjoskar** [comment]
I will close this do to inactivity.
