### ISSUE TITLE
Images are loaded twice

### ISSUE THREAD

**Issue by namerci** [tjoskar/ng-lazyload-image#391]
Hi,

** Problem **
I defined slider in template like that:
```
<div class="slider-container" #sliderElement>
    <div class="slide-item" *ngFor="let slide of slider">
        <a [href]="slide.url">
            <to-image class="slide-image" [image]="slide.image"></to-image>
        </a>

        <a class="btn btn-primary slide-link" [href]="slide.url">{{slide.url_text}}</a>
    </div>
</div>
```

Then initialize slider:
```
tns({
    container: this.sliderElement.nativeElement,
    items: 1,
    slideBy: 'page',
    autoplay: true,
    controls: false,
    prevButton: false,
    nextButton: false,
    autoplayButton: false,
    autoplayButtonOutput: false,
} as any);
```

While `to-image` component is pretty simple:
```
<img *ngIf="isBrowser" class="img-fluid to-image" [defaultImage]="fallback" [lazyLoad]="path" [alt]="alt" (error)="doFallback()">
```

When I have few slides, first slide is loaded correctly. After transition to another slide, every slide is loaded twice (in Google Chrome Dev Tools). 

Why is that?

** Libraries **
ng-lazyload-image: 6.0.0
tiny-slider: 2.9.2
angular: 8.1.0

**EDIT**

It looks like every image on the page is loaded twice. No matter if it's in carousel or standard image. On demo is same problem https://tjoskar.github.io/ng-lazyload-image/

**Comment by tjoskar** [comment]
Hi @namerci,

Have you checked the box "Disable cache"? If so, the image will be loaded twice. If the box is not checked (or devtools is closed) the image should only be loaded once.
You can try this by open devtools, check the "Disable cache"-box. Reload the page (all images will be loaded twice). Uncheck "Disable cache" and reload. The images should now only be loaded once. 
<img width="750" alt="Screenshot 2019-07-10 at 08 36 51" src="https://user-images.githubusercontent.com/1525612/60946401-6d3ad880-a2ee-11e9-8478-fb80952ab91a.png">

**Comment by namerci** [comment]
Oh thanks! You are right!

**Comment by michaelz** [comment]
>  You can try this by open devtools, check the "Disable cache"-box. Reload the page (all images will be loaded twice). Uncheck "Disable cache" and reload. The images should now only be loaded once.

Why is that ? Just curious. This wasn't the case with an older library we used.

**Comment by tjoskar** [comment]
@michaelz, I can't awnser for the other library, but `ng-lazyload-image` will show another image meanwhile the lazyloaded image is loaded. So the flow is:
1. Change the `src`-attribute of the image tag to the default image. (this will trigger a loading of the default image)
2. Load the "real" image by creating a new image tag that is not connected to the dom (eg. `new Img`). This will trigger the image to be loaded.
3. When the image is loaded, we replace the `src`-attribute with the path of the "real"-image. In the normal case; this will not trigger a re-fetch of the image since it is in the cache (no matter of what headers are set on the image, like etag, or last modified) but if the checkbox "Disable cache" is checked if will trigger a new fetch.
