### ISSUE TITLE
Firefox Image transition removing background Image

### ISSUE THREAD

**Issue by Heyjp** [tjoskar/ng-lazyload-image#395]
Hi

I'm encountering an issue with the lazyloading on Firefox browsers. The transition between the defaultImage and the lazyloaded image leaves an empty div with no image briefly. This only seems to happen on the first load up of the page.

Here's an example https://codesandbox.io/s/angular-ng-lazyload-image-3tzh4

Is there any way to prevent this behavior? Thanks

**Comment by tjoskar** [comment]
Hum.. I believe it happens when you load multiple large images. Right now we:
1. Set default image
2. Load the image
3. Append it to the browser

What we should do is something like:
1. Set default image
2. Load the image
3. Decode the image
4. Append it to the browser

See https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode

I'm not sure how easy this is to solve but I will take a look (or it somebody else want to contribute).

Nice catch @Heyjp and thanks for the codesandbox!

**Comment by tjoskar** [comment]
I have taken a look at this and I think I have removed the flicker a little (you can try version 6.1.0-0). But the problem still exist (sometimes).

I would say that the main problem is that you are scaling a 4372x2919 image to a 200x200 and that can not be done before we try rendering it (without creating a separate image, and then a canvas which I think is to complex for this lib).

**Comment by tjoskar** [comment]
I have made some improvement in 6.1.0 but it is not perfect. I guess you have to use more suitable images (regarding the size).

**Comment by Heyjp** [comment]
It wasn't my initial intention to use such large images but just to have a free image to display. But knowing that the issue can be mitigated through having more suitable sizes is really helpful. 

Thanks a lot for looking into this issue and making a quick fix.
