### ISSUE TITLE
Images are not lazy loading when trying to render collection of images  using  *ngFor  and Async pipe

### ISSUE THREAD

**Issue by kumaran-is** [tjoskar/ng-lazyload-image#434]
**Description**
I want to lazy load collection images.  I was trying to  to render collection of images  using  *ngFor  and Async pipe

Here is node code snippets

div class="container-main">
    <div  *ngFor="let image of images$ | async" >
      <img *ngIf="image?.url" [defaultImage]="defaultImage" [lazyLoad]="image?.url">
    </div>
  </div>

Here is the link to launch [ my app in Stackblitz](https://stackblitz.com/github/kumaran-is/ng-lazyload-image-demo)

Github Repo: https://github.com/kumaran-is/ng-lazyload-image-demo

My  Environment
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.23
Node: 12.13.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cli                      8.3.23
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

**Comment by tjoskar** [comment]
Hi @kumaran-is,

Thank you for providing a Stackblitz (and a git repo). 

I spot two issues in your Stackblitz:

1. You are using a http-link to your default image which Stackblitz seams to block so the default image is never loaded. You can easily fix this by just using https instead:

```diff
- defaultImage = "http://via.placeholder.com/2100x80";
+ defaultImage = "https://via.placeholder.com/2100x80";
```

2. It is important to always set a `height` and `width` on images, you will otherwise get "content jumping". You know; when the images and text are jumping around on the page during the load. The reason why all images are loading at the same time in your Stackblitz is because of this. When the page is first loaded all `<img>`-tags have zero height so all images are in the viewport at the beginning. This will make `ng-lazyload-image` to think that every image should be loaded right away. But when the images are loaded they will jump around and some of them will be placed outside the viewport. However, if we tell the browser that we expect an image with a certain height, it will place the images in the right position right away and `ng-lazyload-image` will know that not all images should be loaded right away. This is how I fixed it:
```diff
- <img *ngIf="image?.url" [defaultImage]="defaultImage" [lazyLoad]="image?.url">
+ <img height="1400" width="2096" *ngIf="image?.url" [defaultImage]="defaultImage" [lazyLoad]="image?.url">
```

See the updated Stackblitz here: https://stackblitz.com/edit/github-m6rykc?file=src%2Fapp%2Fapp.component.html

**Comment by kumaran-is** [comment]
Hi @tjoskar  Thanks a lot for detail explanation. Great work, very useful library
