### ISSUE TITLE
In Angular CDK Virtual Scroll, lazy load images with ng-lazyload-image

### ISSUE THREAD

**Issue by kumaran-is** [tjoskar/ng-lazyload-image#435]
**Description**
I would like to know your input, we have implemented virtual scroll using Angular CDK to scroll through a list of images, As we know `Virtual scroll` displays a small subset of records(images in our case) just enough to fill the viewport and re-uses the same DOM elements as the user scrolls. so with `Virtual Scroll` only few DOMs( that are visible in viewport) are created and reused.

Just want to know, will it really make-sense if we use `ng-lazyload-image` to lazy load images in `Virtual Scroll` ? Does it provide any benefits? what is your recommandation . 

I have a created a small apps, with 3 different usecases 
(1) Lazy Load images with  `ng-lazyload-image`
(2) Virtual Scroll using `Angular CDK`
(3) Virtual scroll with lazy loaded images using `Angular CDK`  and  `ng-lazyload-image`

Here is the link to launch [ my Demo app in Stackblitz](https://stackblitz.com/github/kumaran-is/virtual-scroll-demo)

Github Repo: https://github.com/kumaran-is/virtual-scroll-demo

My  Environment
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.23
Node: 12.13.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cli                      8.3.23
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

**Comment by kumaran-is** [comment]
Demo App screen shots with 3 menus for  above mentioned 3 usecases 

![Screen Shot 2020-01-28 at 5 14 03 PM](https://user-images.githubusercontent.com/6869139/73311215-eef34480-41f3-11ea-9f77-d4f049c15504.png)

**Comment by tjoskar** [comment]
Hi @kumaran-is,
First of all, thanks for a detailed issue!

I would say it depends (surprise 😉) on what you want.

The benefit of using `ng-lazyload-image` are:
1. The image will only be loaded when it is in the viewport (faster load time and better for the user's data use)
2. You can show a default image before the real image is loaded. This could be a low-resolution version of the image that loads fast or a standard image that only loads once no matter how many images you are loading.
3. You can fall back on an error image if the real image couldn't be loaded for some reason.

It will, however, come with some costs: Even though this lib is small it will still add some size to your bundle and even though this lib is quite easy it will add some complexity.

Since you are using Virtual Scroll you will get `1.` for free. You will only be adding images while the user is scrolling. However, if the user scrolls fast or is on a bad connection it will only be an empty space where the image should be and if the image could not be loaded it will just be a broken image (see my images below). This issues can be fixed by using `ng-lazyload-image` so my recommendation is to use ng-lazyload-image with Virtual Scroll if:

- You are showing a lot of elements in a list or you are targeting devices with low memory usage (otherwise I do not think there is a point of using Virtual Scroll).
- You want to show another image before the real one has been loaded or you want to fall back on a different image if it couldn't be loaded. 

That's my thoughts anyway.

<img width="648" alt="Screenshot 2020-01-31 at 17 46 13" src="https://user-images.githubusercontent.com/1525612/73558124-d7fe5d80-4452-11ea-9ecc-2e322e9d3aed.png">
<img width="645" alt="Screenshot 2020-01-31 at 17 46 28" src="https://user-images.githubusercontent.com/1525612/73558125-d7fe5d80-4452-11ea-91eb-64b9fae935a8.png">

**Comment by tjoskar** [comment]
I close this due to inactivity. Please let me know it something is unclear.
