### ISSUE TITLE
[Documentation Request] `customObservable` example.

### ISSUE THREAD

**Issue by cpyle0819** [tjoskar/ng-lazyload-image#436]
Hello,

I am attempting to use the `customObservable` attribute on an `img` tag. From what I can understand, it sounds like the `customObservable`'s responsibility is to determine "when the [sic] we should check if the image is in viewport".

I'm using Ionic 3, and I set up a Subject to emit when `ionSlideWillChange` occurs. I've verified this emits when expected, but the images do not seem to update. The default image appears for every slide.

The ng-lazyload-image code seems to suggest that the default observable used here does more than just trigger a check. It looks like it's actually _doing_ the check too.

An example using the custom observable would make this more clear I think.

**Comment by tjoskar** [comment]
Hi,

I'm currently on vacation but I will try to add an example in a couple of days. In the meantime, I can just inform you that `customObservable` is only responsible to tell `ng-lazyload-image` when it should check if the image is in the viewport. It must however implement the rxjs Observable interface. Eg.

```ts
// An Observable that emits an event on every button click.
this.clicks$ = Observable.fromEvent(this.button.nativeElement, 'click');
this.image = 'https://some.nice/image.jpg'
```
```html
<img [customObservable]="clicks$" [lazyLoad]="image">
```

the image above will only be loaded when the user clicks on the button at the same time as the image is in the viewport.

**Comment by tjoskar** [comment]
So it looks like you are on the right track. I will get back on this :)

**Comment by tjoskar** [comment]
Hi again @cpyle0819,

I agree the documentation is lacking in this part. 
Let me try to explain what is happening; when using `customObservable`, the default observable for the current setup is replaced but the other hooks remain the same. Okay, so what does that mean?

The flow for all setups are:
1. setup
2. get event from Observable
3. determine if the image is in viewport based on the event from the Observable in step 2 (and maybe some other factors).
4. load the image
5. set the image into the dom
6. run the finally script (set the css classes and some clean up)

So let say you are using the default intersection observer preset. In this preset we are using the `IntersectionObserver` api, so we do actually already know in step 2 if the image is in the viewport or not. This means that step 3 is really easy to implement. It is just one line:
https://github.com/tjoskar/ng-lazyload-image/blob/9f05aa3945114c9951b21ce8e7dd36f8c7e4a780/src/intersection-observer-preset/preset.ts#L5-L7

This is really nice but what happens if you are using a custom Observable? We will then replace step 2. with our own Observable but keep the rest of the steps intact. So we will need to implement the same api as the `IntersectionObserver`. For example, by include the [`isIntersecting`](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/isIntersecting) key, see: this example: https://stackblitz.com/edit/angular-qtcact?file=src%2Fapp%2Fapp.component.ts

This example will, however, load all images that are using the same `customObservable`. That may or may not be what you want.

The `customObservable`-input was created for use case when we were using the scroll event as observable and we needed a way to pass custom events when we wanted to revalidate if the image was in the viewport or not without having to scroll. But we have since then got the [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) which solves most of these issues so `customObservable` should not bee needed in most use cases.

So back to you question:

> The ng-lazyload-image code seems to suggest that the default observable used here does more than just trigger a check. It looks like it's actually doing the check too.

Yes, this is true for the default, `IntersectionObserver`, preset but not if you are using the [scroll preset](https://github.com/tjoskar/ng-lazyload-image/blob/9f05aa3945114c9951b21ce8e7dd36f8c7e4a780/src/scroll-preset/preset.ts#L7). I do however I agree that this is somewhat confusing.

Are you using the default preset? And what issue are you trying to solve?

**Comment by tjoskar** [comment]
I will close this for now.

**Comment by sagits** [comment]
@tjoskar I needed to change to scrollPreset like you suggested, but I also needed to use the ionSlideDidChange observable instead of the ionSlideWillChange.

By the way, to make it easier for people having a hard time, import it this way:

`        LazyLoadImageModule.forRoot({
            preset: scrollPreset // <-- tell LazyLoadImage that you want to use scrollPreset
          })`
