### ISSUE TITLE
getObservable doesn't work since version 7.0.0

### ISSUE THREAD

**Issue by eun-choi** [tjoskar/ng-lazyload-image#452]
getObservable doesn't work since version 7.0.0

**1) app.module.ts code**

import { LazyLoadImageModule, Attributes } from 'ng-lazyload-image';
import { interval } from 'rxjs';

function getObservable(attributes: Attributes) {
  return interval(100);
}

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    LazyLoadImageModule.forRoot({ getObservable }),
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}

**2) update ng-lazyload-image >= 7.0.0**

**3) ng build or ng run**

**4) Interval doesn't work after running.**

**5) downgrade ng-lazyload-image <= 6.1.0**

**6) ng build or ng run**

**7) Interval function works normally after running.**

**Comment by tjoskar** [comment]
Hi, 
Thanks for the issue. I believe the documentation needs to be more clear on this subject.

The problem you experiencing is because the default preset was changed to `IntersectionObserver` in version 7.0.0.

So if you change the code to this, it should work as previous:
```ts
import { LazyLoadImageModule, Attributes, scrollPreset } from 'ng-lazyload-image';
import { interval } from 'rxjs';

export function getObservable(attributes: Attributes) {
  return interval(100);
}

@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    LazyLoadImageModule.forRoot({ scrollPreset, getObservable }),
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

## The problem 
So why is this? 

In version 6.1.0 we are using the following function to detect if an image is in the viewport or not: https://github.com/tjoskar/ng-lazyload-image/blob/ccbdde70a83233ba277966685719332d5ffd38d2/src/scroll-preset/preset.ts#L7-L22

But in version 7.0.0 and up we are using the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) to detect user interactions and there is no need to detect if the image is in the viewport or not, since the Intersection Observer API is doing that for us. So the function above can now be written as:
https://github.com/tjoskar/ng-lazyload-image/blob/ccbdde70a83233ba277966685719332d5ffd38d2/src/intersection-observer-preset/preset.ts#L5-L7

And here is where the documentation is lacking. When you are using the `IntersectionObserver` preset (which is the default one) you will also need to create your own `isVisible` function. It can be done by:
```ts
imports: [
  LazyLoadImageModule.forRoot({ scrollPreset, getObservable }),
],
```
Or:
```ts
imports: [
  LazyLoadImageModule.forRoot({ isVisible: scrollPreset.isVisible, getObservable }),
],
```
Or creating your own function:
```ts
export const isVisible: IsVisibleFn<MyCustomEvent> = ({ event }) => {
  if (imageIsInViewport(event)) {
    return true;
  } else {
    return false;
  }
};

...

imports: [
  LazyLoadImageModule.forRoot({ isVisible, getObservable }),
],
```

**Comment by eun-choi** [comment]
Thank you for a detailed description!

> import { LazyLoadImageModule, Attributes, scrollPreset } from 'ng-lazyload-image';

> imports: [
  LazyLoadImageModule.forRoot({ isVisible: scrollPreset.isVisible, getObservable }),
],

I've installed version 7.1.0 and changed to that code.
It works very well!
