### ISSUE TITLE
ERROR in node_modules/ng-lazyload-image/src/scroll-hooks/hooks.d.ts(7,51): error TS2304: Cannot find name 'globalThis'.

### ISSUE THREAD

**Issue by fanguangjian** [tjoskar/ng-lazyload-image#466]
I have removed the ng-lazyload-image and install it again, but the error is still there.

**Comment by tjoskar** [comment]
What version of typescript and angular are you using?

**Comment by fanguangjian** [comment]
I use the Angular 7 and typescript 3.1.3. 
The error is still there if I use the ng-lazyload-image  version  8.0.1. 
ERROR in node_modules/ng-lazyload-image/src/scroll-hooks/hooks.d.ts(7,51): error TS2304: Cannot find name 'globalThis'.

**Comment by tjoskar** [comment]
Angular 7 is no longer supported. I only support the same versions as Angular core team: https://angular.io/guide/releases (8, 9 and 10)

The problem here is your typescript version. `globalThis` was introduced in typescript@3.4

So you will need to upgrade Angular or downgrade `ng-lazyload-image`. I hope that helps :)
